core/urls.py
from django.urls import path, include
from account import views as a_views
from . import views

app_name = 'core'

urlpatterns = [
    path('', a_views.sign_in, name='signin'),
    path('home', views.IndexTemplateView.as_view(), name='index'),
]

grest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('product/', include('product.urls'), name='product'),
    path('account/', include('account.urls'), name='account'),
    path('sale/', include('sale.urls'), name='sale'),
]

sale/urls.py
# Imports
from django.urls import path

from sale import views

# Create your urls here.
app_name = "sale"

urlpatterns = [
    path('<int:pk>/add/item', views.add_item_sale, name="add-item-sale"),
    path('<int:pk>/add/snack', views.add_snack, name="add-snack"),
    path('open/list/', views.SaleOpenListView.as_view(), name="sale-open-list"),
    path('<int:pk>/', views.SaleDetailView.as_view(), name='sale-detail'),
    path('new', views.new_sale, name='new-sale'),
    path('<int:pk>/close', views.close_sale, name='sale-close'),
    path('list/', views.SaleListView.as_view(), name="sale-list"),
    path('item/<int:pk>/canceled', views.canceled_item_sale, name='item-sale-canceled'),
]

core/models.py
from django.db import models

# Create your models here.

sale/models.py
# Imports
from django.db import models
from product.models import Product
from django.core.validators import MinValueValidator


class Card(models.Model):
    STATUS_CARD = (
        ("available", "Disponível"),
        ("not_available", "Não Disponível"),
    )
    status = models.CharField(
        "Status", max_length=50, null=False, blank=False,
         choices=STATUS_CARD)

    class Meta:
        verbose_name="Ficha"
        verbose_name_plural="Fichas"

    def __str__(self):
        return str(self.pk)


class Sale(models.Model):
    STATUS_SALE = (
        ("closed", "Fechada"),
        ("open", "Aberta"),
        ("canceled", "Cancelada"),
    )
    TYPE_OF_PAYMENT = (
        ("money", "Dinheiro"),
        ("pix", "Pix"),
        ("credit", "Crédito"),
        ("debit", "Débito"),
    )
    card = models.ForeignKey(Card, verbose_name="Ficha", 
                null=True, blank=False, 
                on_delete=models.CASCADE)
    sale_date = models.DateTimeField(verbose_name="Data da Venda",
                                      auto_now_add=True)
    status = models.CharField(
        "Status", max_length=50, null=False, blank=False,
         choices=STATUS_SALE, default="open")
    type_of_payment = models.CharField(
        "Tipo de Pagamento", max_length=50, null=True, blank=True,
         choices=TYPE_OF_PAYMENT,)
    total = models.DecimalField("Total", decimal_places=2, max_digits=14,
                    validators=[MinValueValidator(0.00)], null=True, blank=True, default=0)

    class Meta:
        verbose_name="Venda"
        verbose_name_plural="Vendas"

    def __str__(self):
        return str(self.pk)


class ItemSale(models.Model):
    STATUS_ITEM_SALE = (
        ("canceled", "Cancelado"),
    )
    product = models.ForeignKey(Product, verbose_name="Produto", 
                null=False, blank=False, 
                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Quantidade", 
                        null=True, blank=True, default=0,
                        validators=[MinValueValidator(0)])
    quantity_snack = models.DecimalField("Quantidade (Kg/g)", decimal_places=3, max_digits=14,
                    validators=[MinValueValidator(0.00)], null=True, blank=True)
    unitary_value = models.DecimalField("Valor Unitário", decimal_places=2, max_digits=14,
                        validators=[MinValueValidator(0.00)], null=False)
    total = models.DecimalField("Total", decimal_places=2, max_digits=14,
                        validators=[MinValueValidator(0.00)], null=False, default=0)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField("Status", max_length=50, null=True, blank=True,
         choices=STATUS_ITEM_SALE)

    class Meta:
        verbose_name="Item de Venda"
        verbose_name_plural="Itens de Venda"

    def __str__(self):
        return str(self.product)

sale/forms.py
# Imports
from django import forms
from .models import Sale, ItemSale, Card, Product
from product.models import Product


class OpenSaleForm(forms.ModelForm):
    card = forms.ModelChoiceField(label="card", queryset=Card.objects.filter(status="available").order_by("pk"))

    class Meta:
        model = Sale
        fields = ['card']


class CloseSaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['type_of_payment']


class ItemSaleForm(forms.ModelForm):
    product = forms.ModelChoiceField(label="Produto", queryset=Product.objects.filter(type_product="sale"))

    class Meta:
        model = ItemSale
        fields = '__all__'
        exclude = ('unitary_value', 'total', 'sale')


class SnackForm(forms.ModelForm):
    product = forms.ModelChoiceField(label="Refeição", queryset=Product.objects.filter(category__name="Refeição"))

    class Meta:
        model = ItemSale
        fields = ['product', 'quantity_snack']
        exclude = ('unitary_value', 'total', 'sale', 'quantity')

core/views.py
# Imports
from django.views.generic import TemplateView

# Create your views here.

class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

sale/views.py
# Imports
from datetime import datetime

from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.views.generic import ListView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from product.models import Product
from .models import Sale, Card, ItemSale
from .forms import OpenSaleForm, ItemSaleForm, CloseSaleForm, SnackForm
from account.permissions import GroupRequiredMixin


class SaleOpenListView(ListView):
    model = Sale
    template_name = 'sale/sale_open_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Sale.objects.filter(status='open').order_by("card")
        context['form'] = OpenSaleForm()

        return context


class SaleDetailView(DetailView):
    model = Sale

    def get_sale(self):
        return get_object_or_404(Sale, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sale = self.get_sale()
        context['sale'] = sale
        context['items'] = ItemSale.objects.filter(sale=sale.pk).exclude(status="canceled").order_by("-pk")
        context['form_item_sale'] = ItemSaleForm()
        context['form_sale'] = CloseSaleForm()
        context['form_add_snack'] = SnackForm()

        return context


@csrf_exempt
def add_item_sale(request, pk):
    sale = Sale.objects.get(id=pk)
    form_item_sale = ItemSaleForm(request.POST)

    if form_item_sale.is_valid():
        product = Product.objects.get(id=form_item_sale.cleaned_data['product'].pk)

        item_sale = ItemSale.objects.create(
            product=product,
            quantity=form_item_sale.cleaned_data['quantity'],
            unitary_value=product.value,
            total=form_item_sale.cleaned_data['quantity']*product.value,
            sale=sale
        )

        messages.success(request, "Item adicionado com sucesso!")
        return redirect(reverse('sale:sale-detail', args=[sale.pk]))


@csrf_exempt
def add_snack(request, pk):
    sale = Sale.objects.get(id=pk)
    form_snack = SnackForm(request.POST)

    if form_snack.is_valid():
        product = Product.objects.get(id=form_snack.cleaned_data['product'].pk)

        item_sale = ItemSale.objects.create(
            product=product,
            quantity_snack=form_snack.cleaned_data['quantity_snack'],
            unitary_value=product.value,
            total=form_snack.cleaned_data['quantity_snack']*product.value,
            sale=sale
        )

        messages.success(request, "Refeição adicionada com sucesso!")
        return redirect(reverse('sale:sale-detail', args=[sale.pk]))


@csrf_exempt
def new_sale(request):
    card = Card.objects.get(id=request.POST['card'])
    card.status = "not_available"
    card.save()

    item_sale = Sale.objects.create(
        card=card
    )

    sale = Sale.objects.get(card=card, status="open")

    messages.success(request, "Comanda aberta com sucesso!")
    return redirect(reverse('sale:sale-detail', args=[sale.pk]))


@csrf_exempt
def close_sale(request, pk):
    sale = Sale.objects.get(id=pk)
    items = ItemSale.objects.filter(sale=sale).exclude(status="canceled")
    total = 0

    for item in items:
        total = total+item.total

    sale.type_of_payment = request.POST['type_of_payment']
    sale.total = total
    sale.status = "closed"
    sale.save()

    card = Card.objects.get(id=sale.card.pk)
    card.status = "available"
    card.save()

    messages.success(request, "Venda encerrada com sucesso!")
    return redirect(reverse('sale:sale-open-list'))


class SaleListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente']
    model = Sale
    queryset = Sale.objects.all().order_by("-sale_date")


@csrf_exempt
def canceled_item_sale(request, pk):
    item = ItemSale.objects.get(id=pk)
    item.status = "canceled"
    item.save()
    
    messages.success(request, "Item cancelado com sucesso!")
    return redirect(reverse('sale:sale-detail', args=[item.sale.pk]))

core/templates/sale/sale_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
{% endblock %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">
            <button type="button" class="btn" onclick="window.history.back();" title="Voltar">
                <i class="fas fa-angle-left fa-2x"></i>
            </button>
            Relatório de Vendas
        </h1>

        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
            
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3" id="mainContainer">
                <div id="myFilter" class="form-group">
                    <form>
                        <div class="form-row">
                            <div class="col-md-3">
                                <label class="mb-2 font-weight-bold text-primary">Relatório</label>
                                <select id="select1" class="form-control form-control-sm">
                                    <option value="*">--- Selecione uma opção ---</option>
                                    <option value="today">Diário</option>
                                    <option value="month">Mensal (Atual)</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="mb-2 font-weight-bold text-primary">Tipo de Pagamento</label>
                                <select id="select2" class="form-control form-control-sm">
                                    <option value="*">--- Selecione uma opção ---</option>
                                    <option value="Cartão">Cartão</option>
                                    <option value="Dinheiro">Dinheiro</option>
                                    <option value="Pix">Pix</option>
                                </select>
                            </div>
                            <div class="col-md-3">
                                <label class="mb-2 font-weight-bold text-primary">Início</label>
                                <input type="date" id="min" class="form-control form-control-sm  date-range-filter" placeholder="Início">
                            </div>
                            <div class="col-md-3">
                                <label class="mb-2 font-weight-bold text-primary">Fim</label>
                                <input type="date" id="max" class="form-control form-control-sm date-range-filter" placeholder="Fim">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="bTable" width="100%" cellspacing="0">
                        <thead class="thead-dark">
                            <tr>
                                <th>Data da Venda</th>
                                <th>Ficha</th>
                                <th>Status</th>
                                <th>Tipo de Pagamento</th>
                                <th>Valor</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <!-- <tfoot class="thead-dark">
                            <tr>
                                <th>Data da Venda</th>
                                <th>Ficha</th>
                                <th>Status</th>
                                <th>Tipo de Pagamento</th>
                                <th>Valor</th>
                                <th>Ações</th>
                            </tr>
                        </tfoot> -->
                        <tbody>
                            {% for sale in object_list %}
                                <tr>
                                    <td>{{sale.sale_date|date:"d/m/Y"}}</td>
                                    <td>{{sale.card}}</td>
                                    <td>{{sale.get_status_display}}</td>
                                    <td>{{sale.get_type_of_payment_display}}</td>
                                    <td>R$ {{sale.total}}</td>
                                    <td style="text-align: center;"><a class="btn btn-success btn-circle btn-sm" href="{% url 'sale:sale-detail' sale.id %}" title="Visualizar Venda"><i class="fas fa-eye"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

{% block scripts %}
    <script>
        var table;
        
        $(document).ready( function () {
            table = $('#bTable').dataTable({
                "dom": "l<'#myFilter'>frtip", 
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Portuguese-Brasil.json",
                },
                "info": false,
            });
        } );

        $("#mainContainer").on("change", "#select1", function () {
            table.fnDraw();
        });

    // Busca na tabela por dia e mês
        $.fn.dataTable.ext.search.push(
        function (settings, data) {
            var status = $("#select1").val();
            col_date_input = data[0] || "";

            // Padronizando a data de hoje no formato brasileiro
            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0');
            var yyyy = today.getFullYear();
            today = dd + "/" + mm + "/" + yyyy;

            var conc = '/' + mm + '/';

            if (status == "today"){
                if(col_date_input == today){
                    return true;
                }else{
                    return false;
                }  
            }
            else if (status == "month") {
                if(col_date_input.includes(conc)){
                    return true;
                }else{
                    return false;
                }  
            }
            else {
                return true;
            }
        });

        // Busca na tabela por tipo de pagamento
        $.fn.dataTable.ext.search.push(
        function (settings, data) {
            var type = $("#select2").val();
            col_type_of_payment = data[3] || "";

            if (type != "*"){
                if(col_type_of_payment == type){
                    return true;
                }else{
                    return false;
                }  
            }
            else {
                return true;
            }
        });

        $("#mainContainer").on("change", "#select2", function () {
            table.fnDraw();
        });
    

    // Busca na tabela por intervalo
        $.fn.dataTable.ext.search.push(
            function(settings, data, dataIndex) {
                var col = data[0]

                var min = $('#min').val();
                var max = $('#max').val();

                var col = col.split("/");
                var col = new Date(col[2], col[1] - 1, col[0]);
                var min = min.split('-').reverse()
                var min = new Date(min[2], min[1] - 1, min[0]);
                var max = max.split('-').reverse()
                var max = new Date(max[2], max[1] - 1, max[0]);

                if ((isNaN(min)) || (isNaN(max))) {
                    return true;
                }
                if (col >= min && col <= max) {
                    return true;
                } else {
                    return false;
                }
        });

        $('.date-range-filter').change(function() {
            table.fnDraw();
        });

    </script>
{% endblock %}

core/templates/sale/sale_open_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
{% endblock %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">
            <button type="button" class="btn" onclick="window.history.back();" title="Voltar">
                <i class="fas fa-angle-left fa-2x"></i>
            </button>
            Comandas em Aberto
        </h1>

        <div class="row">

            <!-- Button trigger modal -->
            <div class="col-md-12 mb-4" style="text-align: right;">
                <a href="#" class="btn btn-primary btn-circle btn-sm" title="Abrir Comanda" data-toggle="modal" data-target=".bd-example-modal-lg">
                    <i class="fas fa-plus"></i>
                </a>
            </div>

            <!-- Modal -->
            <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Abrir Comanda</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                        <div class="modal-body">
                            <form method="post" action="{% url 'sale:new-sale' %}">{% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label>Fichas Disponíveis <span class="text-danger">*</span></label>
                                        {% render_field form.card class="form-control" %}
                                        {% for error in form.card.errors %}
                                            <span class="help-inline text-danger">{{error}}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div style="text-align: right;">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <input type="submit" class="btn btn-primary" value="Abrir"></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        {% if not object_list %}
        <h1 style="text-align: center;" class="m-4 text-gray">
            Não possui comanda aberta no momento!
        </h1>
       {% endif %}

        <div class="row">
            {% for sale in object_list %}
                <!-- Earnings (Monthly) Card Example -->
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="h5 font-weight-bold text-primary text-uppercase mb-1">
                                        <a href="{% url 'sale:sale-detail' sale.pk %}" title="Visualizar Comanda">
                                            Ficha {{sale.card.pk}}
                                        </a>
                                    </div>
                                    <!-- <div class="h6 mb-0 font-weight text-gray-800">R$ <span>{{sale.total}}</span></div> -->
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-scroll fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
    <!-- /.container-fluid -->
    
{% endblock %}

{% block scripts %}
{% endblock %}