core/urls.py
from django.urls import path, include
from account import views as a_views
from . import views

app_name = 'core'

urlpatterns = [
    path('', a_views.sign_in, name='signin'),
    path('home', views.IndexTemplateView.as_view(), name='index'),
]

grest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('product/', include('product.urls'), name='product'),
    path('account/', include('account.urls'), name='account'),
    path('sale/', include('sale.urls'), name='sale'),
]

product/urls.py
# Imports
from django.urls import path

from product import views

# Create your urls here.
app_name = "product"

urlpatterns = [
    path('add/', views.ProductAddView.as_view(), name="add"),
    path('list/', views.ProductListView.as_view(), name="list"),
    path('<int:pk>/edit/', views.EditProductView.as_view(), name='edit'),
    path('input/stock/', views.EntryOfSaleProductIntoStockView.as_view(), name="input-product-stock"),
    path('input/deposit/', views.EntryOfConsumptionProductIntoStockView.as_view(), name="input-product-deposit"),
    path('output/deposit/', views.OutputOfConsumptionProductIntoStockView.as_view(), name="output-product-deposit"),
    path('stock/list/', views.StockListView.as_view(), name="stock-list"),
    path('deposit/list/', views.DepositListView.as_view(), name="deposit-list"),
    path('category/add/', views.CategoryAddView.as_view(), name="category-add"),
    path('input/stock/list/', views.InputOfProductSaleListView.as_view(), name="input-of-product-sale-list"),
    path('output/stock/list/', views.OutputOfProductSaleListView.as_view(), name="output-of-product-sale-list"),
    path('input/deposit/list/', views.InputOfProductConsumptionListView.as_view(), name="input-of-product-consumption-list"),
    path('output/deposit/list/', views.OutputOfProductConsumptionListView.as_view(), name="output-of-product-consumption-list"),
    path('category/list/', views.CategoryListView.as_view(), name="category-list"),
    path('category/<int:pk>/edit/', views.EditCategoryView.as_view(), name='category-edit'),
]

core/models.py
from django.db import models

# Create your models here.

product/models.py
# Imports
from django.db import models
from django.core.validators import MinValueValidator
from django.core.exceptions import ValidationError


class Category(models.Model):
    name = models.CharField("Nome", max_length=200, null=False, blank=False)

    class Meta:
        verbose_name="Categoria"
        verbose_name_plural="Categorias"

    def __str__(self):
        return self.name


class Product(models.Model):
    TYPE_OF_MEASURE = (
        ("kg", "Quilograma"),
        ("ml", "Mililitro"),
        ("l", "Litro"),
        ("g", "Grama"),
        ("un", "Unidade")
    )
    PRODUCT_TYPE = (
        ("consumption", "Consumo"),
        ("sale", "Venda"),
    )

    category = models.ForeignKey(Category, verbose_name=("Categoria"), 
                    null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField("Nome", max_length=200, null=False, blank=False)
    description = models.TextField("Descrição", null=True, blank=True)
    value = models.DecimalField("Valor", decimal_places=2, max_digits=14,
                        validators=[MinValueValidator(0.00)], null=True, blank=True)
    type_of_measure = models.CharField("Unidade de Medida", max_length=2, 
                        null=True, blank=True, choices=TYPE_OF_MEASURE)
    unit_size = models.FloatField("Tamanho da Unidade", null=True, 
                        blank=True, validators=[MinValueValidator(0)])
    purchase_price = models.DecimalField("Preço de Compra", decimal_places=2, max_digits=14,
                        validators=[MinValueValidator(0.00)], null=False, default=0)
    type_product = models.CharField("Tipo de Produto", max_length=11, null=False, 
                    blank=False, choices=PRODUCT_TYPE, default="sale")

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.name


class Stock(models.Model):
    product = models.ForeignKey(Product, verbose_name=("Produto"), 
                        null=False, blank=False, 
                        on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Quantidade em Estoque", 
                        null=False, blank=False, default=0,
                        validators=[MinValueValidator(0)])
    quantity_min = models.PositiveIntegerField(verbose_name="Quantidade Mínima", 
                        null=True, blank=True, default=0, 
                        validators=[MinValueValidator(0)])


    class Meta:
        verbose_name = "Estoque"
        verbose_name_plural = "Estoques"

    def __str__(self):
        return self.product.name


class InputOfProduct(models.Model):
    product = models.ForeignKey(Product, verbose_name=("Produto"), 
                    null=False, blank=False, 
                    on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Quantidade", 
                        null=False, blank=False, default=0,
                        validators=[MinValueValidator(0)])
    entry_date = models.DateTimeField(verbose_name="Data de entrada",
                                      auto_now_add=True)
    expiration_date = models.DateField("Data de validade", null=True, blank=True)


    class Meta:
        verbose_name = "Entrada de Produto"
        verbose_name_plural = "Entrada de Produtos"

    def __str__(self):
        return str(self.product.name)

    def save(self, *args, **kwargs):
        stock = Stock.objects.get(product=self.product)
        stock.quantity += self.quantity
        stock.save()
        super(InputOfProduct, self).save()


class OutputOfProduct(models.Model):
    product = models.ForeignKey(Product, verbose_name=("Produto"), 
                    null=False, blank=False, 
                    on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name="Quantidade", 
                        null=False, blank=False, default=0,
                        validators=[MinValueValidator(0)])
    departure_date = models.DateTimeField(verbose_name="Data de saída",
                                      auto_now_add=True)


    class Meta:
        verbose_name = "Saída de Produto"
        verbose_name_plural = "Saída de Produtos"

    def __str__(self):
        return str(self.product.name)

    def save(self, *args, **kwargs):
        stock = Stock.objects.get(product=self.product)
        if self.quantity <= stock.quantity:
            stock.quantity -= self.quantity
            stock.save()
        else:
            raise ValidationError("Não possui quantidade suficiente desse produto!")
        super(OutputOfProduct, self).save()

product/forms.py
# Imports
import re
import decimal

from django import forms
from .models import Category, Product, InputOfProduct, OutputOfProduct, Stock


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class ProductForm(forms.ModelForm):
    value = forms.CharField(label="Valor", required=False)
    unit_size = forms.FloatField(label="Tamanho", min_value=0, required=False)
    quantity_min = forms.IntegerField(label="Quantidade Mínima", min_value=0, required=False)
    purchase_price = forms.CharField(label="Valor de Compra", required=True)
    
    class Meta:
        model = Product
        fields = ['category', 'name', 'description',    
                 'value', 'type_of_measure', 'unit_size', 
                 'quantity_min', 'purchase_price', 'type_product']

    def clean(self):
        """
            1. Verifica se o campo value (valor de venda) está em branco e se 
            o produto é do tipo sale (venda), caso atenda essas condições
            uma exceção é executada.

            2. Verifica se o campo type_product é do tipo sale e se a categoria é
            None, se a condição for atendida uma exceção é executada.

            3. Verifica se o campo type_product é do tipo sale e se campo unity_size (tamanho)
            é None, caso atenda essa condição, uma exceção é executada.
        """
        cleaned_data = self.cleaned_data
        type_product = cleaned_data.get("type_product")
        value = cleaned_data.get("value")
        category = cleaned_data.get("category")
        unit_size = cleaned_data.get("unit_size")

        if (type_product == "sale" and value == None) or (type_product == "sale" and category == None) or (type_product == "sale" and unit_size == None):
            self._errors["value"] = forms.ValidationError("Este campo é obrigatório caso o produto seja para venda!")

        return cleaned_data


    def clean_value(self):
        if self.cleaned_data['value'] == "":
            return None
        else:
            value = int(re.sub('[^0-9]', '', self.cleaned_data['value']))/100
            value = round(decimal.Decimal(value), 2)

            return value

    def clean_purchase_price(self):
        purchase_price = int(re.sub('[^0-9]', '', self.cleaned_data['purchase_price']))/100
        purchase_price = round(decimal.Decimal(purchase_price), 2)

        return purchase_price


class EntryOfSaleProductIntoStockForm(forms.ModelForm):
    # Formulário de entrada de produtos para venda no estoque
    product = forms.ModelChoiceField(label="product", queryset=Product.objects.filter(type_product="sale").order_by("name"))
    
    class Meta:
        model = InputOfProduct
        fields = ['product', 'quantity', 'expiration_date']
        

class EntryOfConsumptionProductIntoStockForm(forms.ModelForm):
    # Formulário de entrada de produtos para consumo no estoque
    product = forms.ModelChoiceField(label="product", queryset=Product.objects.filter(type_product="consumption").order_by("name"))
    
    class Meta:
        model = InputOfProduct
        fields = ['product', 'quantity', 'expiration_date']


class OutputOfProductForm(forms.ModelForm):
    product = forms.ModelChoiceField(label="product", queryset=Product.objects.filter(type_product="consumption").order_by("name"))
    
    class Meta:
        model = OutputOfProduct
        fields = ['product', 'quantity']

    def clean_quantity(self):
        stock = Stock.objects.get(product=self.cleaned_data['product'])
        if int(self.data['quantity']) > stock.quantity:
            raise forms.ValidationError("Quantidade disponível: " + str(stock.quantity))

        return self.data['quantity']

core/views.py
# Imports
from django.views.generic import TemplateView

# Create your views here.

class IndexTemplateView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

product/views.py
# Imports
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.contrib import messages
from account.permissions import GroupRequiredMixin
from django.views.generic import UpdateView

from .models import Product, Stock, InputOfProduct, OutputOfProduct, Category
from .forms import (ProductForm, EntryOfSaleProductIntoStockForm,
                    EntryOfConsumptionProductIntoStockForm,
                    OutputOfProductForm, CategoryForm)

# Create your views here.
class ProductAddView(GroupRequiredMixin, CreateView):
    group_required = [u'Gerente', u'Caixa']
    template_name = "product/product_add.html"
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('product:list')
    success_message = "Produto cadastrado com sucesso!"

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        product = form.save(commit=False)
        product.save()

        stock = Stock.objects.create(
            product=Product.objects.get(pk=product.pk),
            quantity_min=form.cleaned_data['quantity_min'],
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductAddView, self).get_context_data(**kwargs)
        return context


class ProductListView(ListView):
    model = Product


class EntryOfSaleProductIntoStockView(GroupRequiredMixin, CreateView):
    group_required = [u'Gerente', u'Caixa']
    template_name = "product/input_of_product.html"
    model = InputOfProduct
    form_class = EntryOfSaleProductIntoStockForm
    success_url = reverse_lazy('product:input-product-stock')
    success_message = "Produto adicionado ao estoque!"

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        input_product = form.save(commit=False)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EntryOfSaleProductIntoStockView, self).get_context_data(**kwargs)
        context['type_form'] = "Estoque"
        return context
    

class EntryOfConsumptionProductIntoStockView(GroupRequiredMixin, CreateView):
    group_required = [u'Gerente', u'Caixa']
    template_name = "product/input_of_product.html"
    model = InputOfProduct
    form_class = EntryOfConsumptionProductIntoStockForm
    success_url = reverse_lazy('product:input-product-stock')
    success_message = "Produto adicionado ao depósito!"

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        input_product = form.save(commit=False)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EntryOfConsumptionProductIntoStockView, self).get_context_data(**kwargs)
        context['type_form'] = "Depósito"
        return context


class OutputOfConsumptionProductIntoStockView(GroupRequiredMixin, CreateView):
    group_required = [u'Gerente', u'Caixa']
    template_name = "product/output_of_product.html"
    model = OutputOfProduct
    form_class = OutputOfProductForm
    success_url = reverse_lazy('product:output-product-deposit')
    success_message = "Produto retirado do depósito!"

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        input_product = form.save(commit=False)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(OutputOfConsumptionProductIntoStockView, self).get_context_data(**kwargs)
        return context


class StockListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa'] 
    model = Stock
    queryset = Stock.objects.filter(product__type_product="sale")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_list'] = "Estoque"
        return context
    

class DepositListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa'] 
    model = Stock
    queryset = Stock.objects.filter(product__type_product="consumption")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type_list'] = "Depósito"
        return context


class CategoryAddView(GroupRequiredMixin, CreateView):
    group_required = [u'Gerente', u'Caixa']
    template_name = "product/category_add.html"
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('product:add')
    success_message = "Categoria cadastrada com sucesso!"

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        category = form.save(commit=False)
        category.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CategoryAddView, self).get_context_data(**kwargs)
        return context


class InputOfProductSaleListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa']
    model = InputOfProduct
    queryset = InputOfProduct.objects.filter(product__type_product="sale").order_by("-entry_date")


class OutputOfProductSaleListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa']
    model = OutputOfProduct
    queryset = OutputOfProduct.objects.filter(product__type_product="sale").order_by("-departure_date")
    
    
class InputOfProductConsumptionListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa']
    model = InputOfProduct
    queryset = InputOfProduct.objects.filter(product__type_product="consumption").order_by("-entry_date")


class OutputOfProductConsumptionListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa']
    model = OutputOfProduct
    queryset = OutputOfProduct.objects.filter(product__type_product="consumption").order_by("-departure_date")


class EditProductView(GroupRequiredMixin, UpdateView):
    group_required = [u'Gerente', u'Caixa']
    model = Product
    template_name = 'product/edit_product.html'
    form_class = ProductForm

    def get_success_url(self):
        messages.success(self.request, "Produto atualizado com sucesso!")  
        return reverse('product:list')


class CategoryListView(GroupRequiredMixin, ListView):
    group_required = [u'Gerente', u'Caixa'] 
    model = Category


class EditCategoryView(GroupRequiredMixin, UpdateView):
    group_required = [u'Gerente', u'Caixa']
    model = Category
    template_name = 'product/edit_category.html'
    form_class = CategoryForm

    def get_success_url(self):
        messages.success(self.request, "Categoria atualizada com sucesso!")  
        return reverse('product:category-list')

core/templates/product/category_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
{% endblock %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">
            <button type="button" class="btn" onclick="window.history.back();" title="Voltar">
                <i class="fas fa-angle-left fa-2x"></i>
            </button>
            Categorias
        </h1>
        <!-- <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
            For more information about DataTables, please visit the <a target="_blank"
                href="https://datatables.net">official DataTables documentation</a>.</p> -->

        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
            
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <!-- <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Adicionar Filtros aqui</h6>
            </div> -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead class="thead-dark">
                            <tr>
                                <th>Nome</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <!-- <tfoot class="thead-dark">
                            <tr>
                                <th>Nome</th>
                                <th>Ações</th>
                            </tr>
                        </tfoot> -->
                        <tbody>
                            {% for category in object_list %}
                                <tr>
                                    <td>{{category.name}}</td>
                                    <td style="text-align: center;"><a class="btn btn-warning btn-circle btn-sm" href="{% url 'product:category-edit' category.pk %}" title="Editar Categoria"><i class="fas fa-edit"></i></a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready( function () {
            $('#dataTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.25/i18n/Portuguese-Brasil.json",
                },
                "info": false,
            });
        } );
    </script>
{% endblock %}

core/templates/product/edit_product.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
{% endblock %}

{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            <button type="button" class="btn" onclick="window.history.back();" title="Voltar">
                <i class="fas fa-angle-left fa-2x"></i>
            </button>
            Atualizar Produto
        </h1>
    </div>
    
    <!-- Content Row -->
    <div class="container-fluid">
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post">{% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Nome <span class="text-danger">*</span></label>
                    {% render_field form.name class="form-control" %}
                    {% for error in form.name.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-4">
                    <label>
                        Categoria
                        <a href="{% url 'product:category-add' %}" title="Adicionar Categoria">
                            <i class="fas fa-plus"></i>
                        </a>
                    </label>
                    {% render_field form.category class="form-control" %}
                    {% for error in form.category.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-2">
                    <label>Unidade de Medida <span class="text-danger">*</span></label>
                    {% render_field form.type_of_measure class="form-control" %}
                    {% for error in form.type_of_measure.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-2">
                    <label>Tamanho</label>
                    {% render_field form.unit_size class="form-control" %}
                    {% for error in form.unit_size.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Tipo de Produto <span class="text-danger">*</span></label>
                    {% render_field form.type_product class="form-control" %}
                    {% for error in form.type_product.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>  
                <div class="form-group col-md-4">
                    <label>Valor de Compra <span class="text-danger">*</span></label>
                    {% render_field form.purchase_price class="form-control money2" type="text" %}
                    {% for error in form.purchase_price.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-4">
                    <label>Valor de Venda</label>
                    {% render_field form.value class="form-control money2" type="text" %}
                    {% for error in form.value.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                {% render_field form.description class="form-control" %}
                {% for error in form.description.errors %}
                    <span class="help-inline text-danger">{{error}}</span>
                {% endfor %}
                <div style="text-align: right;">
                    <span class="text-danger small">campos obrigatórios *</span>
                </div>
            </div>
            <div class="form-group" style="text-align: right;">
                <input type="submit" class="btn btn-primary" value="Atualizar">
            </div>
        </form>
    </div>
    <!-- End Content Row -->
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.money2').mask("#.##0,00", {reverse: true});
        });
    </script>
{% endblock %}

core/templates/product/product_add.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block style %}
{% endblock %}

{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">
            <button type="button" class="btn" onclick="window.history.back();" title="Voltar">
                <i class="fas fa-angle-left fa-2x"></i>
            </button>
            Novo Produto
        </h1>
    </div>
    
    <!-- Content Row -->
    <div class="container-fluid">
        {% if messages %}
        <div>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post">{% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Nome <span class="text-danger">*</span></label>
                    {% render_field form.name class="form-control" %}
                    {% for error in form.name.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-4">
                    <label>
                        Categoria
                        <a href="{% url 'product:category-add' %}" title="Adicionar Categoria">
                            <i class="fas fa-plus"></i>
                        </a>
                    </label>
                    {% render_field form.category class="form-control" %}
                    {% for error in form.category.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-2">
                    <label>Unidade de Medida <span class="text-danger">*</span></label>
                    {% render_field form.type_of_measure class="form-control" %}
                    {% for error in form.type_of_measure.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-2">
                    <label>Tamanho</label>
                    {% render_field form.unit_size class="form-control" %}
                    {% for error in form.unit_size.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>Tipo de Produto <span class="text-danger">*</span></label>
                    {% render_field form.type_product class="form-control" %}
                    {% for error in form.type_product.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>  
                <div class="form-group col-md-3">
                    <label>Quantidade Mínima</label>
                    {% render_field form.quantity_min class="form-control" %}
                    {% for error in form.quantity_min.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3">
                    <label>Valor de Compra <span class="text-danger">*</span></label>
                    {% render_field form.purchase_price class="form-control money2" type="text" %}
                    {% for error in form.purchase_price.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
                <div class="form-group col-md-3">
                    <label>Valor de Venda</label>
                    {% render_field form.value class="form-control money2" type="text" %}
                    {% for error in form.value.errors %}
                        <span class="help-inline text-danger">{{error}}</span>
                    {% endfor %}
                </div>
            </div>
            <div class="form-group">
                <label>Descrição</label>
                {% render_field form.description class="form-control" %}
                {% for error in form.description.errors %}
                    <span class="help-inline text-danger">{{error}}</span>
                {% endfor %}
                <div style="text-align: right;">
                    <span class="text-danger small">campos obrigatórios *</span>
                </div>
            </div>
            <div class="form-group" style="text-align: right;">
                <input type="submit" class="btn btn-primary" value="Salvar">
            </div>
        </form>
    </div>
    <!-- End Content Row -->
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function(){
            $('.money2').mask("#.##0,00", {reverse: true});
        });
    </script>
{% endblock %}